Clarify and improve SEO for negation in search
obsidianmd/obsidian-help pull request #459
Opened 2023-05-08 11:31 UTC by nielsbom

The Search page did not use the term "negate" or "negation" which is a term people will use to find this feature.

I also added an example of negating an OR expression in parentheses.

2023-05-08 16:04 UTC, marcusolsson reviewed
Thank you for the suggestions! 🙏 I added a couple of comments. Let me know what you think.

2023-05-08 16:04 UTC, marcusolsson commented on en/Plugins/Search.md
> +- `meeting -(work OR meetup)` returns files that contain `meeting` but do not contain `work` or `meetup`.
```suggestion
- `meeting -(work OR meetup)` returns files that contain `meeting` but not `work` or `meetup`.
```

Keep symmetry with previous examples.

2023-05-08 18:08 UTC, nielsbom commented
Hi @marcusolsson thanks for the quick response.

Using your feedback I updated my PR:

1. "technical term" yep, let's remove that.
2. Simpler = better.
3. Search engines will find "negate" when searching for "negation" so SEO-wise this will have the same result.


My original example of `meeting -(work OR meetup)` is functionally similar to `meeting -work -meetup` which I think is simpler so I added an example using the latter query.

I also added an example for negation of the logical AND (which uses the ` ` operator 😃).

2023-05-11 14:38 UTC, marcusolsson requested changes
Looking over the Search docs, I notice that we don't do a good job at explaining what a query, term, and expression are, and how they relate.

While this PR highlight this problem, I think it can be addressed in a separate PR. Aside from my nitpick, this is good to merge.

2023-05-11 14:38 UTC, marcusolsson commented on en/Plugins/Search.md
> +To exclude or _negate_ a word from the search results, add a hyphen (`-`) in front of it:
```suggestion
To exclude, or _negate_, a word from the search results, add a hyphen (`-`) in front of it:
```

2023-07-20 21:19 UTC, merged

2023-07-20 21:51 UTC, nielsbom commented
🎉