Clarified what settings are recommended when exporting from Notion
obsidianmd/obsidian-help pull request #627
Opened 2023-11-22 14:27 UTC by Sire

and importing into Obsidian.
I was never sure what to select.

2023-12-16 19:15 UTC, sharkmu requested changes

2023-12-16 19:15 UTC, sharkmu commented on en/Import notes/Import from Notion.md
> +10. You're done!
kinda unnecessary

2023-12-26 02:32 UTC, sigrunixia approved these changes

2023-12-26 02:32 UTC, sigrunixia commented
Thank you for the PR. I will merge this in with my other changes tomorrow. :)

2023-12-26 02:54 UTC, merged